/**
 * Delete Site Dialog.
 *
 * When the site has deployments it can't be deleted, so it shows a
 * blocker with a link to the Deployments page instead of the
 * type-to-confirm delete flow.
 */

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { AlertTriangle } from "lucide-react";
import { sitesApi } from "../../api/sites";
import type { SiteWithStats } from "../../api/types";
import { invalidateProjectData } from "../../lib/invalidate-project";
import { Button } from "../ui/button";
import { Callout } from "../ui/callout";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog";
import { TypeToConfirmDialog } from "../ui/type-to-confirm-dialog";

interface DeleteSiteDialogProps {
  site: SiteWithStats | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DeleteSiteDialog({
  site,
  open,
  onOpenChange,
}: DeleteSiteDialogProps) {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const { projectId } = useParams<{ projectId: string }>();

  const deleteMutation = useMutation({
    mutationFn: () => sitesApi.delete(site!.id),
    onSuccess: () => {
      // Site deletion nulls out site_id on any linked deployments and
      // changes site filter options / map overlays. Blanket invalidate.
      if (projectId) {
        invalidateProjectData(queryClient, projectId);
      }
      queryClient.invalidateQueries({ queryKey: ["sites-with-stats", projectId] });
      onOpenChange(false);
    },
    onError: (error: Error) => {
      console.error("Failed to delete site:", error);
    },
  });

  if (!site) return null;

  // Blocked: the site still has deployments. Point the user at the
  // Deployments page rather than offering a delete.
  if (site.deployment_count > 0) {
    return (
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-destructive" />
              Delete site
            </DialogTitle>
            <DialogDescription>
              This site cannot be deleted while it has deployments.
            </DialogDescription>
          </DialogHeader>

          <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
            <p className="text-sm font-medium text-destructive mb-2">
              This site has {site.deployment_count} deployment
              {site.deployment_count === 1 ? "" : "s"}
            </p>
            <p className="text-sm text-destructive/90">
              To avoid orphaning data, deployments must be handled first. You can
              reassign them to a different site or delete them from the Deployments page.
            </p>
          </div>

          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button
              type="button"
              onClick={() => {
                onOpenChange(false);
                navigate(`/projects/${projectId}/deployments`);
              }}
            >
              Go to deployments
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    );
  }

  return (
    <TypeToConfirmDialog
      open={open}
      onOpenChange={onOpenChange}
      title="Delete site"
      description="This action cannot be undone. This will permanently delete the site."
      confirmWord={site.name}
      confirmLabel="Delete site"
      pendingLabel="Deleting..."
      onConfirm={() => deleteMutation.mutate()}
      isPending={deleteMutation.isPending}
      error={deleteMutation.error?.message ?? null}
      variant="destructive"
    >
      <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
        <p className="text-sm font-medium text-destructive mb-2">
          Warning - This will permanently delete
        </p>
        <ul className="text-sm text-destructive/90 list-disc list-outside pl-5 space-y-1">
          <li>The site and all its metadata</li>
          <li>Any tags and custom fields</li>
        </ul>
      </div>

      <Callout variant="info">
        Your original images and videos will not be deleted. Only data
        generated by AddaxAI will be removed.
      </Callout>
    </TypeToConfirmDialog>
  );
}
