"""Verify that unhandled exceptions surface as proper 500s with CORS headers.

Cara's broken-DB diagnostic reproduced a subtle CORS interaction:
starlette's default ServerErrorMiddleware sits OUTSIDE CORSMiddleware,
so a 500 response generated by an unhandled exception had no
`Access-Control-Allow-Origin` header. In Electron (where the renderer
is loaded from `localhost:8000` but the API is called at
`127.0.0.1:8000`, a cross-origin pair) the renderer reported every
such 500 as `TypeError: Failed to fetch`, hiding the real backend
status code and the real error message.

The app registers an `@app.exception_handler(Exception)` to catch
unhandled exceptions and return a JSON 500 through the normal
middleware chain, which includes CORSMiddleware. The tests below
exercise that.
"""

from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient


@pytest.fixture()
def error_client():
    """Test client with a route that always raises plus our exception handler.

    Patches `init_db` for the same reason `tests/conftest.py:client` does:
    we are exercising middleware, not migrations.

    The failing route is injected at the FRONT of `app.routes` so the
    SPA catch-all (`/{full_path:path}`) does not match it first.
    """
    from fastapi.routing import APIRoute

    from app.main import create_app

    with patch("app.main.init_db"):
        app = create_app()

        def _boom() -> dict:
            raise RuntimeError("intentional test failure")

        # Inject ahead of the SPA catch-all so the route matches.
        app.routes.insert(
            0,
            APIRoute("/api/__test_500__", _boom, methods=["GET"]),
        )

        # raise_server_exceptions=True is the default and is what we
        # need here: starlette's TestClient with =False suppresses the
        # exception before our handler gets a chance to run and
        # returns an empty 500 body instead. With =True the inner
        # exception flows through the normal middleware chain and our
        # @app.exception_handler(Exception) intercepts it.
        with TestClient(app) as c:
            yield c


def test_unhandled_exception_returns_500(error_client: TestClient) -> None:
    """500 response, not a propagated test-client exception."""
    response = error_client.get("/api/__test_500__")
    assert response.status_code == 500
    assert response.json() == {"detail": "Internal Server Error"}


def test_unhandled_exception_response_has_cors_header(
    error_client: TestClient,
) -> None:
    """500 response carries the CORS allow-origin header.

    Without this, the renderer in Electron reports the response as
    `TypeError: Failed to fetch` and the real status code never
    reaches diagnostics.
    """
    response = error_client.get(
        "/api/__test_500__",
        headers={"Origin": "http://localhost:5173"},
    )
    assert response.status_code == 500
    assert (
        response.headers.get("access-control-allow-origin")
        == "http://localhost:5173"
    )
