/**
 * Delete Deployment Dialog with type-to-confirm.
 *
 * Deletion cascades to files, events, and detections in the database.
 * Files on disk are not touched.
 */

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { deploymentsApi } from "../../api/deployments";
import { invalidateProjectData } from "../../lib/invalidate-project";
import { Callout } from "../ui/callout";
import { TypeToConfirmDialog } from "../ui/type-to-confirm-dialog";

export interface DeleteDeploymentTarget {
  id: string;
  site_name: string;
  start_date_local: string;
}

interface DeleteDeploymentDialogProps {
  deployment: DeleteDeploymentTarget | null;
  projectId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DeleteDeploymentDialog({
  deployment,
  projectId,
  open,
  onOpenChange,
}: DeleteDeploymentDialogProps) {
  const queryClient = useQueryClient();

  const deleteMutation = useMutation({
    mutationFn: () => deploymentsApi.delete(deployment!.id),
    onSuccess: () => {
      // Deletion cascades to files, detections, and events. Blanket
      // invalidate so every page reflects the removed data.
      invalidateProjectData(queryClient, projectId);
      queryClient.invalidateQueries({ queryKey: ["sites-with-stats", projectId] });
      onOpenChange(false);
    },
    onError: (error: Error) => {
      console.error("Failed to delete deployment:", error);
    },
  });

  if (!deployment) return null;

  return (
    <TypeToConfirmDialog
      open={open}
      onOpenChange={onOpenChange}
      title="Delete deployment"
      description="This action cannot be undone. This will permanently delete the deployment and all associated data."
      confirmWord="DELETE"
      confirmLabel="Delete deployment"
      pendingLabel="Deleting..."
      onConfirm={() => deleteMutation.mutate()}
      isPending={deleteMutation.isPending}
      error={deleteMutation.error?.message ?? null}
      variant="destructive"
    >
      <div className="text-sm">
        <p className="text-muted-foreground">Deployment</p>
        <p className="font-medium">
          {deployment.site_name} - {deployment.start_date_local}
        </p>
      </div>

      <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
        <p className="text-sm font-medium text-destructive mb-2">
          Warning - This will permanently delete
        </p>
        <ul className="text-sm text-destructive/90 list-disc list-outside pl-5 space-y-1">
          <li>The deployment and all its metadata</li>
          <li>All file records, observations, and events</li>
          <li>All human verifications on those observations</li>
        </ul>
      </div>

      <Callout variant="info">
        Your original images and videos will not be deleted. Only data
        generated by AddaxAI will be removed.
      </Callout>
    </TypeToConfirmDialog>
  );
}
