"""add deployment warnings column

Revision ID: 2540e6edbee2
Revises: 03e058c707df
Create Date: 2026-05-11 12:41:41.539399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2540e6edbee2'
down_revision: Union[str, None] = '03e058c707df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('warnings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'warnings')
    # ### end Alembic commands ###
