"""initial schema

Revision ID: 9c173fff3bcd
Revises:
Create Date: 2026-04-29 21:13:33.699589

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c173fff3bcd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_log', ['created_at_utc'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_created', 'jobs', ['created_at_utc'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('label_taxonomy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classification_model_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('taxon_class', sa.String(length=100), nullable=True),
    sa.Column('taxon_order', sa.String(length=100), nullable=True),
    sa.Column('taxon_family', sa.String(length=100), nullable=True),
    sa.Column('taxon_genus', sa.String(length=100), nullable=True),
    sa.Column('taxon_species', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification_model_id', 'name', 'project_id', name='uq_label_taxonomy_model_name_project')
    )
    op.create_index('idx_label_taxonomy_model', 'label_taxonomy', ['classification_model_id'], unique=False)
    op.create_index('idx_label_taxonomy_name', 'label_taxonomy', ['name'], unique=False)
    op.create_index('idx_label_taxonomy_project', 'label_taxonomy', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detection_model_id', sa.String(length=100), nullable=False),
    sa.Column('classification_model_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_model_id', sa.String(length=100), nullable=True),
    sa.Column('excluded_classes', sa.JSON(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('detection_threshold', sa.Float(), nullable=False),
    sa.Column('event_smoothing', sa.Boolean(), nullable=False),
    sa.Column('smoothing_strength', sa.String(length=20), nullable=False),
    sa.Column('taxonomic_rollup', sa.Boolean(), nullable=False),
    sa.Column('taxonomic_rollup_threshold', sa.Float(), nullable=False),
    sa.Column('independence_interval', sa.Integer(), nullable=False),
    sa.Column('shortcut_labels', sa.JSON(), nullable=False),
    sa.Column('video_fps', sa.Float(), nullable=False),
    sa.Column('min_cluster_size', sa.Integer(), nullable=False),
    sa.Column('min_samples', sa.Integer(), nullable=False),
    sa.Column('detection_batch_size', sa.Integer(), nullable=True),
    sa.Column('classification_batch_size', sa.Integer(), nullable=True),
    sa.Column('embedding_batch_size', sa.Integer(), nullable=True),
    sa.Column('postprocessing_settings_hash', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('habitat_type', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_site_name_per_project')
    )
    op.create_table('deployment_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('datetime_offset_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('deployment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('folder_path', sa.Text(), nullable=True),
    sa.Column('folder_status', sa.String(length=20), nullable=False),
    sa.Column('last_validated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date_local', sa.Date(), nullable=False),
    sa.Column('end_date_local', sa.Date(), nullable=True),
    sa.Column('camera_model', sa.String(length=255), nullable=True),
    sa.Column('camera_serial', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('datetime_offset_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployments_site_id'), 'deployments', ['site_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('event_start_local', sa.DateTime(), nullable=False),
    sa.Column('event_end_local', sa.DateTime(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_deployment', 'events', ['deployment_id'], unique=False)
    op.create_index('idx_events_local', 'events', ['event_start_local', 'event_end_local'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('captured_at_local', sa.DateTime(), nullable=False),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('observation_type', sa.String(length=20), server_default='unclassified', nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('best_frame_number', sa.Integer(), nullable=True),
    sa.Column('best_frame_path', sa.Text(), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('source_video_id', sa.String(length=36), nullable=True),
    sa.Column('source_frame_number', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('verified_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('favorited', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('flagged', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('flagged_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_captured_at_local', 'files', ['captured_at_local'], unique=False)
    op.create_index('idx_files_deployment', 'files', ['deployment_id'], unique=False)
    op.create_index('idx_files_flagged', 'files', ['flagged'], unique=False)
    op.create_index('idx_files_source_video', 'files', ['source_video_id'], unique=False)
    op.create_index('idx_files_verified', 'files', ['verified'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('label_confidence', sa.Float(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('original_label', sa.String(length=100), nullable=True),
    sa.Column('original_label_confidence', sa.Float(), nullable=True),
    sa.Column('label_taxonomy_id', sa.String(length=36), nullable=True),
    sa.Column('classification_method', sa.String(length=20), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['label_taxonomy_id'], ['label_taxonomy.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detections_category', 'detections', ['category'], unique=False)
    op.create_index('idx_detections_confidence', 'detections', ['confidence'], unique=False)
    op.create_index('idx_detections_file', 'detections', ['file_id'], unique=False)
    op.create_index('idx_detections_frame_number', 'detections', ['frame_number'], unique=False)
    op.create_index('idx_detections_job', 'detections', ['job_id'], unique=False)
    op.create_index('idx_detections_label', 'detections', ['label'], unique=False)
    op.create_index('idx_detections_label_confidence', 'detections', ['label_confidence'], unique=False)
    op.create_index('idx_detections_label_taxonomy', 'detections', ['label_taxonomy_id'], unique=False)
    op.create_index('idx_detections_original_label', 'detections', ['original_label'], unique=False)
    op.create_index('idx_detections_verified', 'detections', ['verified'], unique=False)
    op.create_table('event_files',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'file_id')
    )
    op.create_index('idx_event_files_event', 'event_files', ['event_id'], unique=False)
    op.create_index('idx_event_files_file', 'event_files', ['file_id'], unique=False)
    op.create_table('event_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('label_taxonomy_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('max_n', sa.Integer(), nullable=False),
    sa.Column('max_n_file_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_taxonomy_id'], ['label_taxonomy.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['max_n_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'label_taxonomy_id', name='uq_event_obs_event_taxonomy')
    )
    op.create_index('idx_event_obs_event', 'event_observations', ['event_id'], unique=False)
    op.create_index('idx_event_obs_label', 'event_observations', ['label'], unique=False)
    op.create_index('idx_event_obs_label_taxonomy', 'event_observations', ['label_taxonomy_id'], unique=False)
    op.create_table('detection_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('detection_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('embedding_model_id', sa.String(length=100), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('l2_norm', sa.Float(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detection_embeddings_detection', 'detection_embeddings', ['detection_id'], unique=False)
    op.create_index('idx_detection_embeddings_detection_model', 'detection_embeddings', ['detection_id', 'embedding_model_id'], unique=True)
    op.create_index('idx_detection_embeddings_model', 'detection_embeddings', ['embedding_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_detection_embeddings_model', table_name='detection_embeddings')
    op.drop_index('idx_detection_embeddings_detection_model', table_name='detection_embeddings')
    op.drop_index('idx_detection_embeddings_detection', table_name='detection_embeddings')
    op.drop_table('detection_embeddings')
    op.drop_index('idx_event_obs_label_taxonomy', table_name='event_observations')
    op.drop_index('idx_event_obs_label', table_name='event_observations')
    op.drop_index('idx_event_obs_event', table_name='event_observations')
    op.drop_table('event_observations')
    op.drop_index('idx_event_files_file', table_name='event_files')
    op.drop_index('idx_event_files_event', table_name='event_files')
    op.drop_table('event_files')
    op.drop_index('idx_detections_verified', table_name='detections')
    op.drop_index('idx_detections_original_label', table_name='detections')
    op.drop_index('idx_detections_label_taxonomy', table_name='detections')
    op.drop_index('idx_detections_label_confidence', table_name='detections')
    op.drop_index('idx_detections_label', table_name='detections')
    op.drop_index('idx_detections_job', table_name='detections')
    op.drop_index('idx_detections_frame_number', table_name='detections')
    op.drop_index('idx_detections_file', table_name='detections')
    op.drop_index('idx_detections_confidence', table_name='detections')
    op.drop_index('idx_detections_category', table_name='detections')
    op.drop_table('detections')
    op.drop_index('idx_files_verified', table_name='files')
    op.drop_index('idx_files_source_video', table_name='files')
    op.drop_index('idx_files_flagged', table_name='files')
    op.drop_index('idx_files_deployment', table_name='files')
    op.drop_index('idx_files_captured_at_local', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_events_local', table_name='events')
    op.drop_index('idx_events_deployment', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deployments_site_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_table('deployment_queue')
    op.drop_table('sites')
    op.drop_table('projects')
    op.drop_index('idx_label_taxonomy_project', table_name='label_taxonomy')
    op.drop_index('idx_label_taxonomy_name', table_name='label_taxonomy')
    op.drop_index('idx_label_taxonomy_model', table_name='label_taxonomy')
    op.drop_table('label_taxonomy')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
