import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar is auto-generated from the folder structure under docs/.
// To add a page: drop a .md/.mdx file into a folder. To add a section:
// create a folder with a _category_.json file. Ordering is controlled by
// `sidebar_position` in each page's frontmatter and by `position` in
// _category_.json. No edits here needed for normal content changes.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
